### PR TITLE
Fix #72: mkdir for datafile if necessary

### LINKED ISSUE #72: When setting `ZSHZ_DATA` to an XDG basedir location, the directory doesn't get created
One of the annoyances I've always had with rupa/z is that if you set `_Z_DATA` to an XDG compliant location (https://github.com/agkozak/zsh-z/issues/20), you have to make sure the directory exists with something like this:

```zsh
_Z_DATA=${XDG_DATA_HOME:=$HOME/.local/share}/z/data
if [[ ! -f $_Z_DATA ]]; then
  mkdir -p ${_Z_DATA:h}
  touch $_Z_DATA
fi
```

I tried zsh-z and it suffers from the same issue:

```zsh
ZSHZ_DATA=${XDG_DATA_HOME:=$HOME/.local/share}/zsh-z/data

# error: zshz:28: no such file or directory: ~/.local/share/zsh-z/data
```

If a user sets the path they want to use for the z database, zsh-z should create it for them. Would you accept a PR that changes this line... https://github.com/agkozak/zsh-z/blob/82f5088641862d0e83561bb251fb60808791c76a/zsh-z.plugin.zsh#L164

...to this?

```zsh
[[ -f $datafile ]] || { mkdir -p "${datafile:h}" && touch "$datafile" }
```

### PR DESCRIPTION
**Pull request by mattmc3**
See #72

### CODE REVIEW

**Comment by mattmc3** [comment]
Also, I verified that if ZSHZ_DATA is set to a file name with no directory path, the `:h` suffix will helpfully return '.'. This will ensure that `mkdir -p` succeeds on that edge case.

```zsh
ZSHZ_DATA=my_z_database

# the h param expansion returns '.' in this case
echo ${ZSHZ_DATA:h}

# mkdir -p won't fail on this edge case
mkdir -p ${ZSHZ_DATA:h}
```

**Comment by agkozak** [comment]
Thank you for the very clever solution.

I wonder if we should do anything further about the edge case. If I accidentally put in my `.zshrc`

    ZSHZ_DATA=quux

instead of

    ZSHZ_DATA=~/quux

Zsh-z will happily create a `quux` file in every directory I navigate to. That is literally what I told it to do, but it's presumably never what I want.

I should be able to address this issue early next week.

**Comment by mattmc3** [comment]
> Zsh-z will happily create a quux file in every directory I navigate to. That is literally what I told it to do, but it's presumably never what I want.

That's a great callout. I pushed another one-liner commit that addresses this:

```
[[ "${datafile:h}" !=  '.' ]] || datafile="${ZDOTDIR:-$HOME}/$datafile"
```

Let me know if how I handled it works for you. It might seem a bit clever, but I think it reads pretty clear that the basedir isn't '.' or set the dir to where zsh considers home.

**Comment by agkozak** [comment]
Your addition was great. I just merged it to `master`. Thanks again!

**Pull request merged**
